apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-env
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    RENOVATE_TOKEN: "AgAjoo22unxIG68H4v5ylSpgW4u07cJhQtQiDyAkYAg3ETMfeuBQuos8VedN6Hq+xfu2qkXAZa2EYZvOV1+AnQd2LJWV00yfeAma4kWCRPmFVpl+qABO995zbpYeiiV45Q65ch8lLMRE86hqCR/XlHdxoy7i800lQJKb4WN2jGfAqcZXOz7vaGUrQg5cix3EK8SIQ8khO/qMa/lYPsHxpwo0aI+ixk90u5RM2mCHNYCDxeHb/NU8SCV0xRoeoW/xF6XgWXJBaKhVn7rjvxoRtd/DAEvbHtcqyWYsmQGujKPYKWF60hdKjFYpu44juGVt6LVteCjCyiWSJfGOuN0Rx9Mpam7r207mIEcsCL35E4ombmi0YpKx8JkG6WQd1okwXqgJcUe9TDCO0kfry3YXyOoD46IkNJlKWnQF+yzA96v8drfC9Z268YCb8MItahdUX+eWbBwqyiyA+SXFwH502y47ygOmqvt01FyzUpwmpGryYSC523bDz0dKgrGja3G8TgUJLGM0b7DyFXi6d9r5EeZ+MEs33wqQ/v2iAdzaDUtnlPgvH6GpYSsBCWP+d+7vhnwmIXJLqouWOxGJyGX+pYMK0d+NawXnHPpK1oQiyXG+T/Hfi+pbhSVM4hrvNOqi3n/MQo1QJDXXO1AyY4O146YkH4aJ5KuXlLVP48OhdpZDYktUpn1BlL1S+/svAoy5Ta5ZoxfYwRSUbqeUeq0vQ/bq3zQw+psYNzKDpvd1aGTQWkiKWY1nlJkz"
