apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
  finalizers: []
spec:
  project: default
  source:
    path: kgtkr/datadog
    repoURL: https://github.com/kgtkr/public-cd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
