apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-private
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kgtkr/ingress-nginx-private
    repoURL: https://github.com/kgtkr/public-cd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-private
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
