apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-event-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kgtkr/kubernetes-event-exporter
    repoURL: https://github.com/kgtkr/public-cd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-event-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
