apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-minio
  source:
    path: kgtkr/longhorn-minio
    repoURL: https://github.com/kgtkr/public-cd
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
