apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers: []
spec:
  project: default
  source:
    path: kgtkr/longhorn
    repoURL: https://github.com/kgtkr/public-cd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
