apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: discord-wake-up-bot
  name: discord-wake-up-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: discord-wake-up-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discord-wake-up-bot
    spec:
      nodeSelector:
        kubernetes.kgtkr.net/node-lan: home
      tolerations:
        - key: kubernetes.kgtkr.net/unreliable
          effect: NoSchedule
      containers:
        - image: ghcr.io/kgtkr/discord-wake-up-bot:20220516001743174-1a56e54
          name: discord-wake-up-bot
          resources:
            requests:
              cpu: "10m"
              memory: "15Mi"
          volumeMounts:
            - mountPath: /etc/discord-wake-up-bot
              name: discord-wake-up-bot-config
              readOnly: true
          env:
            - name: CONFIG_DIR
              value: /etc/discord-wake-up-bot
            - name: TZ
              value: Asia/Tokyo
      restartPolicy: Always
      volumes:
        - name: discord-wake-up-bot-config
          secret:
            secretName: discord-wake-up-bot-config
