apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    DISCORD_TOKEN: AgC3QYv8XALOUeEJOy139xzNe4Hg6QxjOSlMfML4oYsUGPIB4ZdLY8ImsA5ITznkmcIUPpMTwwXHCR3ZN4vwJ5GOlz0LSDn2DxGu+4ofwXQSN+w7YwsUvHZXikrBji7UWuYmO0Q5TG+NwI+w7h8c3RBgD1Qx9Qm0Y1yPHpB90IurLUeyeN1SEdIn78XMVgq5AZ5jla4Pn1pizDuXE8iYQwon2iO0bOSlSyCgH8AvHklKJ8doQx17liYRH9VRSk/0ZtckYzI+axP/ciQyGfH4t9gUsU32SzQDXLudynm/wfGvssc9IEi2p3Wptlpxv6Ii/beWZXdovFT6h+bpw9nxTu45e9ouPj0Iy93xCfJpx53J6ruTEOm3WLmP0iXZmMfektBefgwi4qDTmib9yOqun7Mgx8MbLHUtP5ZMqXr0l4InqbbgnPGrzQvpF6neZgdzOZzpmbi1FUN4X+Pg+HLSJkrpti6e/GJqEPOYwftotVfaopDC+7CHAT9XXD3INdnCbNdDXcTOXZaoAp9kRz2lJAdyhPNJQH+QIFDyXL4ffUo4XqFKioY3zXRQqhWX5JL9RCLVmSin9+ioGWokDQVoO31Cx9oawwkbXoNRClZaxQhkjo7Ja40AWV9zaiJ5cRP8+ZR8lACeV/MDtM8bKP0BQFQghxnhnYMMsiwx/x4To3HZfVC0zbGU059GeMZSj6M3fa3cLcAQjo3m1HW1RZD0L9+0/KqNmjMxP/p0uWSKl8BDJUE69iyDSIg0XjU6JYsAkhU7vZsBBb7Bn2SJKg==
