apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acme-dns01-cloudflare-api-key
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    apikey: AgAHS++JfpjRE/ap/E3eHHvsW1qOndD6h06k9q539/0w9OCPfiebNVF5/ffpb16G5/z9v9k8ky+5HQuMlxCwYUX0ky/ppIPocftZhT1G45w8mBTFGxejNkog8CADBI+g/B7EcLaT5SxlX4Aa7fBCpYnXCsFsONRHJK65QEnal0Z79MZeu8ecCtVp6UbR5leb5RhKPUvaySwRfWfxVFaYuSmKzB+JNk/K7JHeM7zHi3CABx8rnKk9HuTZi95Du9cRRA80VGcSPp1z7mnHqILKKArcB8eAQq8eorsUR95GtL9jeH59WIKi9iAcaysMqF83K9p8XHmiVLYeIfAtqhmJs5rxd6A9HhbxEbG0PZ82ytjJCSA8/+IFrJcfSreFV8IeQixWE/Rsqfdg56FvBpcpD9vjfGOZhhZL2LQ5Z6Qx1oVl3f8QvsEeQOcre66D/l6+SszsqJuIMSmrRWIauGcnt38im8kuCqd4Pqins8vDdQIeMROXxxVsCelVwuvnirBDUh9iUjInKutPubWmiIujLYrqGkiatRE9+bCdb3kbCDPMgnezkS/VSSwIVgMQ7w0lWkoUCl/EWv05o9luthO41DkrcRhgRVhSrUVa/EP0bcM7syVrrczrd76bzUCDxsl2AJ2J4ex1lX3hkwOp8bfnkg2tQWujJSeVIZENUdar6qtu3LNHaxUHZqcZIymSQV3bpkNjcX4OjpivQZjV7LOZbwNS3EGwQ8dp7w5VXWEVX+gFjvMZelQJjMhZ
