apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubernetes-event-exporter
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    SLACK_TOKEN: AgBVodgYshB0mKxRNzBhbv5i3KWfKtiqwk5m5PQP4Ke4TigrGZRQSyifR8PWUZSb/iPeDBP6Spzcc2wt/jc/LKx88F1OwRzqGKM30lLgvcPOe+eYHoDsp3+fnlLNYDLNG8fQbNSri6Nkwg+puFYq3tjnLMZilQtKD3hW+Whxg79IlLzMOc2u2vDehEr+vbBgKcq1c0BNIYc37NQzBABc72LMRm42BZZaf52sgjum1YKw+1/Uwpwgz2kpjI6eKnJy0rR7YhdsewUTg1hYniUHO4LCFTZJgHyBpSB+xlv1C7gVRzXSCs9B4KHfA6p1gITYCL9oToU67SDB6m+CMevnN18xSx6qCyfF997GJ49D5Qst0Qjw4Z/Ik1DVx6deyNJ94d5ijMCgE1qwM485SUJBJJVWMwh/ADc4HTDfmug8pb67+Ydf2srOvAzx2DoxpOrByAJ5VWzdB7QODaXsNtILHLp+OEgyjgfFw7EDvWbMgjWxx1szpqhB/EEMgvOzn41zGeLmmvrZ9bQZyhYWLx2uWpHvlYigM0JjWNJ4E+Lv7eqWCCJqZXDIwxDygjgTf1yVYaBx+UeC7gXhjumI44722p2YMo8n/YdOGcLv+U1AOPU2KLR0EGrLWE0ddwAwQa6QLvPsd1iZbPU/7HRoGIg8bjNX52j4K4Hv4ppIS6pJ/9eOyX07aBE+Jiu1dqFBJ0omguzzNi7AFEnGJViGnXPDtLz/syJenTS7NTbihh5Ts7vcXPDKZqvBAnfyZzH/X+MvSQ2xiuecS6TXRDc=
