apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup: enabled
    recurring-job.longhorn.io/snapshot: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeName: minecraft-bedrock-server-idv
