apiVersion: v1
kind: ConfigMap
metadata:
  name: unmined-web-indexhtml
data:
  unmined-web-index.html: |
    <!DOCTYPE html>
    <html lang="en">
    
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>kgtkr mc idv - unmined</title>
    </head>
    
    <body>
      <ul>
        <li><a href="/overworld">overworld</a></li>
        <li><a href="/nether">nether</a></li>
        <li><a href="/end">end</a></li>
      </ul>
    </body>
    
    </html>
