apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    slack-token: AgBYsOlyud7TnJH4ztiUm7WRe/Iom0Cu5I4dwCQ6dLN/zJlaB+dor9/2nM+sq0GR5fJK55GAQzR25h+h1J6wI2T4XNCnQ7Kt6YpG5fgtYeKMK1bzSqN0D7uD6PhJ8BbsKkCf+acuNX8RIcoLn3wxZlLlwaU717uYdnhoOvDZKFjHERlT3bDYI8rE07SN3jPk+Bek7sstQXmqHfuZjJJSq1LMnsOeoY2ENfThKmmB7ZAKYj7i5DH3QZKim6YsfL0usUwMMYluxCPRfHVUrEHTkhKVw0QADAdkt0pn7D4yCrSgvbDzkxIyXSaSfwiJXRUIP0wJi4zJ7oM4RTzdDWdkPIjgAqnrO5gFpNy7jnjvOSmJqzRvOqQwkkwAa8lHzyZwy+kS3gCJD+GU12ZXC6QU4tK+1bTgHvedfBMXKAd/sO1Q7kZw7JccHKgV7+afRbDM49O0XNJgPusU0a8oK75iya+pzAIugCC/GXDPiaWetOEQAljvNwr8Dstg2QVqVI5/nu1Iqv/3NTom2ODIt9pQiKXtHKPaNKryVVR+w4InHuTF/JSDKosG5Y3803NANlJOV+0XC0ydFpbdH4HI0ZN4J4M97I0z0iy1+vFLyoWItvnQ/INcMdSclLI1SQARtYUC3jYMVufPUFlIBendNLQMlMjIbR5cvFq3WrQ/QqNKTyAjZj0yIqBXK6JcgODWBiSVenOtxLz6bLJdxi+hBcmhStzKHxR0bNOuU2q2TPXjrdlS+yFt+RSOUaC2UvbgNfglAxcehUHjTQ3Pmms=
