apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-wake-up-bot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: public-cd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: discord-wake-up-bot
  source:
    path: kgtkr/discord-wake-up-bot
    repoURL: https://github.com/kgtkr/public-cd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
