apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-category-join-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: public-cd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: discord-category-join-manager
  source:
    path: kgtkr/discord-category-join-manager
    repoURL: https://github.com/kgtkr/public-cd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
