apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nature-remo-temperature-adjuster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: public-cd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: nature-remo-temperature-adjuster
  source:
    path: kgtkr/nature-remo-temperature-adjuster
    repoURL: https://github.com/kgtkr/public-cd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
