apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    DISCORD_TOKEN: AgCBBek0zLO9eUQBRroQY3AxHCNzgKWgaNtYTKt6DBmYtiU4MCBFTP4FQ6jWn4OaVZHGRxMoiHO0lse8eYbWo92xxYAwXNTJN7eJF/DFTkXmLAG6pplirAcevqNBURHaJz2IGjv83Uw70fjKwkas0sg6mbLO4CeyZucE6YI2oj4bfJDWnD7k9+EZXWrW4gfKqlrqqqxL43RU2K8Z3hIEl+9rFXWlSHNqIIfaTCqFB+qd+cnAtPQW+riD8eCAlQhkcxRjh1wr1PkdpfXJOW5kxbBhjRwBGyr0HHkF8eyGXws7KHxXO1WNVCtdcCjrUJAQN44Lmymb5gpYd8CC5pzLPSpAC9KoVMPTkMQNwWdcB4n9b7a8IWk6soVs5GIvphrDcoOVu8HXNtetLr7VS/i7imvJHISlcRyXFPXjEnDEU0Fau/QpyB7PSjS/oNSKJ0QsfQxEOQGBKEmdeG1D9CWwrUTv+HUTG0dTDGCRHjuABSDBfDzRgb5XUsB54LDQpyUpe5m9Ubn8sIvHltvmk0SfahUJDawAQ9/5IaCL3AeXMT51eQXnHLQMN5x7DO5JnwtqRnh+F6a9fzWIBz/FJATo6at7f36JfTgc1SEC4+XkAiMPvnpL4dMCrqtWbSyirJlObCFmxp+42qK9hMiFEWB/GEHAOFStgSQd8f7VJl0Pscq1RNUv+/m98+iTupPvxPbagzgoe+DL8fa+lVezsSMcHCvwi/9Edc2G7zmnef5eOM0HaOpJREU0x/VyyvRgYUUd3zs5H3vHf2NSlRX0El48te8yZiyozSLVueM=
