apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
spec:
  addresses:
    - 192.168.11.10-192.168.11.30
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ips
spec:
  addresses:
    # can
    - 163.44.96.193/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-ips
spec:
  addresses:
    # can
    # - 192.168.190.64/32
    # pypn
    - 192.168.190.62/32
    # saba
    - 192.168.190.45/32
    # nico
    - 192.168.190.68/32
    # cope
    - 192.168.190.47/32

  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
spec:
  ipAddressPools:
    - default
    - public-ips
    - local-ips
