apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    auth: AgAMbdWCfTgZ6i0EEwcoKKYJ5JHYbzLY/VF5AhoXGA4k+9HJDAYQXo9gTR3rRg1Ry3LjR8+YbAK3y2UTxRP9DqL039kNLf/5jO2/tmZaprbqC6xx6I5CITdQZGSEpvbDr01OvfQl0XmfPf+gu0AGkBT2KJF8xvDcDxwupeYtUNwpA9HOqIb+iUdATba8Ai8dLsQdpmIiX9qH5M4grLIScs2gc7o7lJpHsF8F1ybwHfYpKBA8v6iR+efpvyNFTG+taRDlPGgjCF5IpHDBPtdPA8duLXyFthN9jlCNig9bhGelLESpRSnrg0TAX6EiHi9iG/Q8t6g+3rfeX4DQuFsG86+/1N/N5P+DsZ543FnnyvaQRHdDAbje7yhPtleYLMXU9C2qEib/pvCAcK9g8BjyCjRJmqDqZDMWLAVVcrBlsz1Bw5+UsFquhv7q/xLmBSYbmVqNviJcKKSbRNwjKunmxp1CegRunLEjM479BjXx2pFqPvICyWUumW9ARBnqqGLK14gh936EqCTez2Hy6r59FEcoOwSdYxikVJ2+qHgdF7I2SvGP9FZNb0Xdh/AjpHwrau7iNSbIi5xMbx8sMmQGbWtzfj6AuX359kORzSewbZYA82c6w8a8jq+Zz41r8frHe1h0F5TtmSITmZk3FEoB20Ig2K8oDNAIUsOnBJ4J/5qvlIf0/WXrKQKsCrzURfyKrpuMf9jfvvA7Aul3ghQYsAF4EyKr7qGzCGBxl8ckbVesz6O+DsM8uv8Q3bwz
