apiVersion: v1
kind: Service
metadata:
  name: es
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  ports:
    - port: 9200
  selector:
    app.kubernetes.io/name: es
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: es
  serviceName: es
  template:
    metadata:
      labels:
        app.kubernetes.io/name: es
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - image: ghcr.io/kgtkr/elasticsearch-mastodon:20230713051640465-0fd2954
          name: es
          resources:
            requests:
              cpu: "30m"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
              subPath: data
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
      restartPolicy: Always
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: elasticsearch-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/filesystem-trim: enabled
    recurring-job.longhorn.io/snapshot: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
  volumeName: mastodon-elasticsearch
