resources:
  - postgres.yaml
  - redis.yaml
  - web.yaml
  - streaming.yaml
  - sidekiq.yaml
  - minio.yaml
  - ingress.yaml
  - es.yaml
  # 毎デプロイ/Sync毎に全検索インデックス再構築が走り長時間化するため手動実行とする
  #- search-deploy.yaml
  - db-migrate.yaml
  - prune-profiles.yaml
  - remove-orphans.yaml
  #- remove-media.yaml
  - minio-console-ingress.yaml
  - mastodon-secret.yaml
  - mastodon-config.yaml
  - minio-config.yaml
configMapGenerator:
  - name: minio-policy
    files:
      - policy.json

images:
  - name: ghcr.io/kgtkr/mastodon
    newTag: 20260728153415426-0875e6e-mstdn.kgtkr.net
