apiVersion: batch/v1
kind: Job
metadata:
  name: search-deploy
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      tolerations:
        - key: "kubernetes.kgtkr.net/unreliable"
          effect: "NoSchedule"
      containers:
        - image: ghcr.io/kgtkr/mastodon
          name: app
          resources:
            requests:
              cpu: "10m"
              memory: "300Mi"
          args:
            - tootctl
            - search
            - deploy
          envFrom:
            - secretRef:
                name: mastodon-config
            - secretRef:
                name: mastodon-secret
      restartPolicy: Never
