apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    auth: AgBKJDnjjlLMfsbgupFO3D6TkE5tJOWKOG943bC6P+UQ4d6I0hKoQHJxIcQNMcfxAFutrLoJFPyh5lRXSKTe0TLpUQWiszMjnuaX5texYYCmq5QyLUNB6pmwZ5DSXKaHv6WFaCKx16jb+R+40mGDbM/rkCQCf9UK7F/OWiMWToP/HLDhk4NSRz3QKXdOXP6sx9YxSOi08lQyrISjybUJojFI+qOXPMZ2gfdfCgR4Et1O+cjhFt33BWID4+Av+zQh8j5Se9VobknGjd/0Q0XHand8DRMwu54bUMfLoRXpxKCdLPAeMutLlokU0ddZWCNL6E7D/OhtFeUMdXHaqo9c7amltYzueUw54RsJ/rcY83WvupUImYgjVLLbgCpU2T0cHVuLFNi39GshoveIUr3T5YqnPSDV7qtFOX++b0460Tt7TjAIKTGuEIbukm8tgem9Po5hygeJZAUU1cC+lhIRo9FP5Tfl9S4n8pBLc3Swb7xqX3I2mQPkpjtSaUBnD1QzQUgC1HUfqDTVKrHQHz2tUpRMJtottQPUE67OoVbi/SgJcl2WuAyCLeA1BE9cLl2dd0FBbOi9UhGU89d+f1i52ungilUYugGEcjxwKdQ7gH6HNBaVxdxPwCxxMM2k/FU+WHPpqQbzVPwPHZ8IwzCJo0+Mf8WQ28U9E/jkxy9OhIEm/SnEUELB1TQDS3umPynzYTipsh09B3+zmZm8c9AKCjlO0bjmCwPPZ1k2ZHPPRiUbdsNya1hHkSzQKeA9
