apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    api-key: AgBUZ0lmd18IsX02nzv4GckhoOfXytYNiNfDycZ3g4jIdPhQImK4QamZeVnc1BOphgVS2P2YZSPaxIUu4saU1S3YADe4uIoh01y+QEaefKTFdiwNJlUEQ5AGbhfCN+x82+B4SN0JRUmj9sjjNOXqtcGaE1G107a1UHiSNuiG+PDG8D524IOghoPi0WI+M0FQU62otrCI0iXV5EfCjewVtrY7f4VYsuIjnGZIOq6Tb6POS8y5+YhpT60wPJl5OeKe4yjPSdbdzZwaBVb4gqZ0nGxlcCQamRdvhwrxKCN8jvhZ66yzdjdV9bMeFFJJ7lKkksbi3QAj/8x6Sy2wjVxkK2LIhlVwT1ZfOYoPi6N2ehoTwDuyMeayTRiOzOcarZ/NKNrmN+7nlsasIiti6R1Xd18Zcn95CxzdcfbUPOnhqEWMu2568cij/Go8nwkUWKHkcKSNA2oBknST4gsvKvNPkpOgLYGVtBwSYYWND9+GWM2Bq0VdSIu1pmYdFH10jbrKGgfQOxigDgSAoWsDz608d4/jiZbDDuGDgHzF/20IApBP8cjKm0TdkHZnM9w+NK8YvV3Jl0aUYnTGBCse9MoHa5ZjJi0fV/9MHINRd7pwrVxb2AqW+Q+JXm56RjPH1+bXOX4VZ2NRpDcurb3jEqzsejq1T1wsLgNskygTEl6xKnp8TkyYbv6jUUKK75xr5jXQJ/Jx6ZduemwppUf6dFNgVHQNkni+FGQ7mIbUOVc4hgzRpg==
