apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    token: AgB3ulwNftjLXWrWgr5v4XBy6B6uHLrvcBYtMbE5clbtn1OsBvjO68pynLmWhBWxKZk+HBrm1gIsStd5Sbc+gRE7ejQ+KfKW79NZ4DZJcXaoYc+v7cKegoSTRbzTU2tOoaDZaRy8o4oQ5BTG+EA2VAFMFd5twwu2jSMk31yJzg9nBnOLSqfm2k3ttv10asAUHDyZNJwjME1a1E8JJJSzzHhqn+WTzdlCn6LNLUZ9r+Ee8ztK1zLBq9HdIjQI+Y9fB5yRLEmLAT9XwPjS+1SPS/JkeCkwsviqQcG/DAZZv4ZOCcoCF2QD7J8zs7dxed8WY3TGljHWShZuvOCE9cZpedpVyseco1JaKpvg4jwT6wTW6m59Lh1YQTD60OOTtbgB35jN167/ejxbDefmMNkeLYZjN2ytps5jkwpe3R+7wjejKt5kQav6O+qyNMTEd9DZiwEiVO9nNSE6n/mg05bctHmNozNaJkY83XHtrJdljeCU50PNpo7M/NSnvqJNE4hGcJ4F4mKjTa+MfRH4uAyPzjD2YFP+G2fYf6OzockmMJTQYH0bfYn1R5C5mMVtivdnuXfCw7KHIDKWcitP+RT0hQ3wAs8GqjAdaDvM8r5gXa/RraXhnFIjxRW2ehlGnM18IOZxZkkP7S0NzohLlvJ9c0tzEtOv7R65RV29Za6qxojBi0GT6Gkc0UpnXlwCmQcuSuk5gK6E3VIUj2ObdREpafZRf4DKqFfZGFo1c2BK3l2RQ/82vtfImAfF
